apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-pipeline
spec:
  workspaces:
    - name: output
spec:
  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: output

    - name: lint
      taskRef:
        name: flake8

    - name: test
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output
